docs_dir: docs/book
site_dir: docs/html
extra:
  project: API
  current_version: v7
  versions:
    - v7
    - v6
    - v5
    - v4
nav:
  - Home: index.md
  - v7:
      - Introduction: v7/introduction/introduction.md
      - Overview:
          - "Server Requirements": v7/introduction/server-requirements.md
          - "File Structure": v7/introduction/file-structure.md
          - "Packages": v7/introduction/packages.md
          - "PSRs": v7/introduction/psr.md
      - Installation:
          - "Getting Started": v7/installation/getting-started.md
          - "Composer": v7/installation/composer.md
          - "Configuration Files": v7/installation/configuration-files.md
          - "Doctrine ORM": v7/installation/doctrine-orm.md
          - "Test the Installation": v7/installation/test-the-installation.md
          - "FAQ": v7/installation/faq.md
      - Upgrading:
          - "Upgrade procedure": v7/upgrading/upgrading.md
          - "Upgrading 6.x to 7.0": v7/upgrading/UPGRADE-7.0.md
          - "Upgrading 5.x to 6.0": v7/upgrading/UPGRADE-6.0.md
      - Flow:
          - "Middleware Flow": v7/flow/middleware-flow.md
          - "Default Library Flow": v7/flow/default-library-flow.md
          - "Library Flow for Email": v7/flow/library-flow-for-email.md
      - Core Features:
          - "Authentication": v7/core-features/authentication.md
          - "Authorization": v7/core-features/authorization.md
          - "Content Validation": v7/core-features/content-validation.md
          - "Exceptions": v7/core-features/exceptions.md
          - "Dependency Injection": v7/core-features/dependency-injection.md
          - "Error reporting": v7/core-features/error-reporting.md
          - "Rendering and Sending emails": v7/core-features/rendering-and-sending-emails.md
      - Extended features:
          - "Core and App": v7/extended-features/core-and-app.md
          - "New Handler Structure": v7/extended-features/handler-structure.md
          - "Route Grouping": v7/extended-features/route-grouping.md
          - "Problem Details": v7/extended-features/problem-details.md
          - "Injectable Input Filters": v7/extended-features/injectable-input-filters.md
      - Commands:
          - "Create admin account": v7/commands/create-admin-account.md
          - "Generate database migrations": v7/commands/generate-database-migrations.md
          - "Display available endpoints": v7/commands/display-available-endpoints.md
          - "Generate tokens": v7/commands/generate-tokens.md
      - Tutorials:
          - "Setting up CORS": v7/tutorials/cors.md
          - "Creating a book module": v7/tutorials/create-book-module.md
          - "Creating a book module using DotMaker": v7/tutorials/create-book-module-via-dot-maker.md
          - "Token authentication": v7/tutorials/token-authentication.md
          - "API Evolution": v7/tutorials/api-evolution.md
          - "Find user by identity": v7/tutorials/find-user-by-identity.md
      - Transition from API Tools:
          - "Laminas API Tools vs Dotkernel API": v7/transition-from-api-tools/api-tools-vs-dotkernel-api.md
          - "Transition Approach": v7/transition-from-api-tools/transition-approach.md
          - "Discovery Phase": v7/transition-from-api-tools/discovery-phase.md
      - OpenAPI:
          - "Introduction": v7/openapi/introduction.md
          - "Initialized Components": v7/openapi/initialized-components.md
          - "Write Documentation": v7/openapi/write-documentation.md
          - "Generate Documentation": v7/openapi/generate-documentation.md
          - "Render Documentation": v7/openapi/render-documentation.md
          - "Use Documentation": v7/openapi/use-documentation.md
          - "Getting Help": v7/openapi/getting-help.md
      - Basic Security:
          - "Basic Security": v7/security/basic-security.md
          - "OAuth2 Security": v7/security/oauth2-security.md
      - Reference:
          - "Anonymize Accounts": v7/reference/account-anonymization.md
  - v6:
      - Introduction: v6/introduction/introduction.md
      - Overview:
          - "Server Requirements": v6/introduction/server-requirements.md
          - "File Structure": v6/introduction/file-structure.md
          - "Packages": v6/introduction/packages.md
          - "PSRs": v6/introduction/psr.md
      - Installation:
          - "Getting Started": v6/installation/getting-started.md
          - "Composer": v6/installation/composer.md
          - "Configuration Files": v6/installation/configuration-files.md
          - "Doctrine ORM": v6/installation/doctrine-orm.md
          - "Test the Installation": v6/installation/test-the-installation.md
          - "FAQ": v6/installation/faq.md
      - Upgrading:
          - "Upgrade procedure": v6/upgrading/upgrading.md
          - "Upgrading 5.* to 6.0": v6/upgrading/UPGRADE-6.0.md
      - Flow:
          - "Middleware Flow": v6/flow/middleware-flow.md
          - "Default Library Flow": v6/flow/default-library-flow.md
          - "Library Flow for Email": v6/flow/library-flow-for-email.md
      - Core Features:
          - "Authentication": v6/core-features/authentication.md
          - "Authorization": v6/core-features/authorization.md
          - "Content Validation": v6/core-features/content-validation.md
          - "Exceptions": v6/core-features/exceptions.md
          - "Dependency Injection": v6/core-features/dependency-injection.md
          - "Error reporting": v6/core-features/error-reporting.md
          - "Rendering and Sending emails": v6/core-features/rendering-and-sending-emails.md
      - Extended features:
          - "Core and App": v6/extended-features/core-and-app.md
          - "New Handler Structure": v6/extended-features/handler-structure.md
          - "Route Grouping": v6/extended-features/route-grouping.md
          - "Problem Details": v6/extended-features/problem-details.md
          - "Injectable Input Filters": v6/extended-features/injectable-input-filters.md
      - Commands:
          - "Create admin account": v6/commands/create-admin-account.md
          - "Generate database migrations": v6/commands/generate-database-migrations.md
          - "Display available endpoints": v6/commands/display-available-endpoints.md
          - "Generate tokens": v6/commands/generate-tokens.md
      - Tutorials:
          - "Setting up CORS": v6/tutorials/cors.md
          - "Creating a book module": v6/tutorials/create-book-module.md
          - "Creating a book module using DotMaker": v6/tutorials/create-book-module-via-dot-maker.md
          - "Token authentication": v6/tutorials/token-authentication.md
          - "API Evolution": v6/tutorials/api-evolution.md
          - "Find user by identity": v6/tutorials/find-user-by-identity.md
      - Transition from API Tools:
          - "Laminas API Tools vs Dotkernel API": v6/transition-from-api-tools/api-tools-vs-dotkernel-api.md
          - "Transition Approach": v6/transition-from-api-tools/transition-approach.md
          - "Discovery Phase": v6/transition-from-api-tools/discovery-phase.md
      - OpenAPI:
          - "Introduction": v6/openapi/introduction.md
          - "Initialized Components": v6/openapi/initialized-components.md
          - "Write Documentation": v6/openapi/write-documentation.md
          - "Generate Documentation": v6/openapi/generate-documentation.md
          - "Render Documentation": v6/openapi/render-documentation.md
          - "Use Documentation": v6/openapi/use-documentation.md
          - "Getting Help": v6/openapi/getting-help.md
      - Basic Security:
          - "Basic Security": v6/security/basic-security.md
          - "OAuth2 Security": v6/security/oauth2-security.md
      - Reference:
          - "Anonymize Accounts": v6/reference/account-anonymization.md
  - v5:
      - Introduction: v5/introduction/introduction.md
      - Overview:
          - "Server Requirements": v5/introduction/server-requirements.md
          - "File Structure": v5/introduction/file-structure.md
          - "Packages": v5/introduction/packages.md
          - "PSRs": v5/introduction/psr.md
      - Installation:
          - "Getting Started": v5/installation/getting-started.md
          - "Composer": v5/installation/composer.md
          - "Configuration Files": v5/installation/configuration-files.md
          - "Doctrine ORM": v5/installation/doctrine-orm.md
          - "Test the Installation": v5/installation/test-the-installation.md
          - "FAQ": v5/installation/faq.md
      - Upgrading:
          - "Upgrade procedure": v5/upgrading/upgrading.md
          - "Upgrading 5.2 to 5.3": v5/upgrading/UPGRADE-5.3.md
      - Flow:
          - "Middleware Flow": v5/flow/middleware-flow.md
          - "Default Library Flow": v5/flow/default-library-flow.md
          - "Library Flow for Email": v5/flow/library-flow-for-email.md
      - Core Features:
          - "Authentication": v5/core-features/authentication.md
          - "Authorization": v5/core-features/authorization.md
          - "Content Validation": v5/core-features/content-validation.md
          - "Exceptions": v5/core-features/exceptions.md
          - "Dependency Injection": v5/core-features/dependency-injection.md
          - "Error reporting": v5/core-features/error-reporting.md
      - Commands:
          - "Create admin account": v5/commands/create-admin-account.md
          - "Generate database migrations": v5/commands/generate-database-migrations.md
          - "Display available endpoints": v5/commands/display-available-endpoints.md
          - "Generate tokens": v5/commands/generate-tokens.md
      - Tutorials:
          - "Setting up CORS": v5/tutorials/cors.md
          - "Creating a book module": v5/tutorials/create-book-module.md
          - "Token authentication": v5/tutorials/token-authentication.md
          - "API Evolution": v5/tutorials/api-evolution.md
          - "Find user by identity": v5/tutorials/find-user-by-identity.md
      - Transition from API Tools:
          - "Laminas API Tools vs Dotkernel API": v5/transition-from-api-tools/api-tools-vs-dotkernel-api.md
      - OpenAPI:
            - "Introduction": v5/openapi/introduction.md
            - "Initialized Components": v5/openapi/initialized-components.md
            - "Write Documentation": v5/openapi/write-documentation.md
            - "Generate Documentation": v5/openapi/generate-documentation.md
            - "Render Documentation": v5/openapi/render-documentation.md
            - "Use Documentation": v5/openapi/use-documentation.md
            - "Getting Help": v5/openapi/getting-help.md
      - Reference:
            - "Anonymize Accounts": v5/reference/account-anonymization.md
  - v4:
      - Introduction: v4/introduction/introduction.md
      - Overview:
          - "Server Requirements": v4/introduction/server-requirements.md
          - "File Structure": v4/introduction/file-structure.md
          - "Packages": v4/introduction/packages.md
      - Installation:
          - "Getting Started": v4/installation/getting-started.md
          - "Composer": v4/installation/composer.md
          - "Configuration Files": v4/installation/configuration-files.md
          - "Doctrine ORM": v4/installation/doctrine-orm.md
          - "Test the Installation": v4/installation/test-the-installation.md
          - "FAQ": v4/installation/faq.md
      - Flow:
          - "Middleware Flow": v4/flow/middleware-flow.md
          - "Default Library Flow": v4/flow/default-library-flow.md
          - "Library Flow for Email": v4/flow/library-flow-for-email.md
      - Core Features:
          - "Authentication": v4/core-features/authentication.md
          - "Authorization": v4/core-features/authorization.md
          - "Content Validation": v4/core-features/content-validation.md
          - "Exceptions": v4/core-features/exceptions.md
          - "CORS": v4/core-features/cors.md
      - Commands:
          - "Create admin account": v4/commands/create-admin-account.md
          - "Generate database migrations": v4/commands/generate-database-migrations.md
          - "Display available endpoints": v4/commands/display-available-endpoints.md
          - "Generate tokens": v4/commands/generate-tokens.md
      - Tutorials:
          - "Creating a book module": v4/tutorials/create-book-module.md
          - "Token authentication": v4/tutorials/token-authentication.md
      - Transition from API Tools:
          - "Laminas API Tools vs Dotkernel API": v4/transition-from-api-tools/api-tools-vs-dotkernel-api.md
site_name: api
site_description: "Dotkernel API"
repo_url: "https://github.com/dotkernel/api"
plugins:
  - search
